/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package centrodeacopio;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.accessibility.AccessibleContext;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.border.Border;

/**
 *
 * @author Kenia
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
     */
    /* ExecutorService ejecutor = Executors.newCachedThreadPool();
    ColaBloqueo<Integer> cola = new ColaBloqueo<>(20);*/
    int contadorEntrega = 0;
    int contadorRecoje = 0;
    JLabel labels[] = new JLabel[20];

    public Interfaz() {
        initComponents();
        jPanel1.setLayout(new GridLayout(4, 5));

        for (int i = 0; i < labels.length; i++) {
            JLabel label = new JLabel("", (int) CENTER_ALIGNMENT);
            label.setBackground(Color.GRAY);
            label.setOpaque(true);
            label.setPreferredSize(new Dimension(50, 50));
            label.setMaximumSize(new Dimension(50, 50));
            Border border = BorderFactory.createLineBorder(Color.DARK_GRAY, 5);
            label.setBorder(border);
            labels[i] = label;
            jPanel1.add(labels[i]);

        }

    }

    public void setLabels(JLabel[] labels) {
        this.labels = labels;
    }

    public void changeJLabelEntrega(String text, int i) {
        jLabelEntrega.setText(text);
        //  labels[i].setBackground(Color.YELLOW);
        labels[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("box.png")));
        this.repaint();
    }

    public void changeJLabelRecoje(String text, int i) {
        jLabelRecoje.setText(text);
        //   labels[i].setBackground(Color.GRAY);
        labels[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("delivery.png")));

        this.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelEntrega = new javax.swing.JLabel();
        jLabelRecoje = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 700));

        jPanel1.setPreferredSize(new java.awt.Dimension(300, 250));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Raleway ExtraBold", 0, 18)); // NOI18N
        jLabel2.setText("Estantería");

        jLabel3.setFont(new java.awt.Font("Raleway ExtraBold", 0, 24)); // NOI18N
        jLabel3.setText("Centro de Acopio");

        jLabelEntrega.setFont(new java.awt.Font("Raleway Black", 0, 24)); // NOI18N
        jLabelEntrega.setText("0");

        jLabelRecoje.setFont(new java.awt.Font("Raleway Black", 0, 24)); // NOI18N
        jLabelRecoje.setText("0");

        jLabel4.setFont(new java.awt.Font("Raleway ExtraBold", 0, 18)); // NOI18N
        jLabel4.setText("Entrega");

        jLabel5.setFont(new java.awt.Font("Raleway ExtraBold", 0, 18)); // NOI18N
        jLabel5.setText("Recoje");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRecoje, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(275, 275, 275)
                    .addComponent(jLabel3)
                    .addContainerGap(503, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelRecoje))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jLabel3)
                    .addContainerGap(608, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(1000, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });

    }

    /*    public class Hilo implements Runnable {

        ColaBloqueo<Integer> cola;
        int numero;
        boolean insertar;

        public Hilo(ColaBloqueo<Integer> cola, int numero) {
            this.cola = cola;
            this.numero = numero;
        }

        public Hilo(ColaBloqueo<Integer> cola, int numero, boolean insertar) {
            this.cola = cola;
            this.numero = numero;
            this.insertar = insertar;
        }

        @Override
        public void run() {

            if (insertar) {
                //System.out.println("+Se inserto en : [" + numero + "] - valor : " + numero);
                cola.insertar(numero);
            } else {
                cola.remover();
            }

        }

    }

    public class ColaBloqueo<E> {

        private int max;
        private LinkedList<E> cola;

        // concurrencia
        private ReentrantLock bloqueo = new ReentrantLock(true);
        private Condition noVacio = bloqueo.newCondition();
        private Condition noLleno = bloqueo.newCondition();

        public ColaBloqueo(int max) {
            this.max = max;
            this.cola = new LinkedList<>();
        }

        public void insertar(E element) {

            bloqueo.lock();

            try {

                while (cola.size() == max) {
                    noLleno.wait();
                }

                cola.add(element);
                jLabelEntrega.setText(String.valueOf(element));
                jLabelEntrega.repaint();
                System.out.println("Se inserto en : [" + cola.size() + "] - valor : " + element);
                noVacio.signalAll();

            } catch (Exception e) {

            } finally {
                bloqueo.unlock();
            }
        }

        public E remover() {
            bloqueo.lock();

            try {

                while (cola.size() == 0) {
                    noVacio.wait();
                }

                E element = cola.remove();
                System.out.println("Se removi� en : [" + cola.size() + "] - valor : " + element);
                jLabelRecoje.setText(String.valueOf(element));
                jLabelRecoje.repaint();
                noLleno.signalAll();
                return element;

            } catch (Exception e) {

                return null;
            } finally {
                bloqueo.unlock();
            }

        }

        public void print() {
            for (int i = 0; i < this.cola.size(); i++) {
                //System.out.println("Se inserto en : [" + i + "] - valor : " + cola.get(i));

            }
        }

    }
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelEntrega;
    private javax.swing.JLabel jLabelRecoje;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
